//! topology lane — multi-bus vehicle-network routing and isolation.
//!
//! Purpose (docs/costar_microcar_dogfood_plan.md, "Dogfood Lanes > 3. topology"):
//! force a realistic multi-bus vehicle network and assert costar routes CAN
//! frames correctly across it:
//!
//! * **Expected receivers get each frame** — every other node on the injected
//!   bus records a `can-rx` for it.
//! * **Unexpected receivers do not** — no node on any other bus records it.
//! * **No duplicate injection** — each expected receiver gets it exactly once.
//!
//! ## How
//!
//! Each topology scenario is a set of named CAN buses with machines attached as
//! nodes (a gateway is the shared multi-interface hub). Traffic is generated by
//! `[[bus_inject]]` probes using **unique CAN ids** (0x07xx, never used by the
//! ECU protocol), so each probe's `can-rx` events are unambiguously attributable
//! from today's trace (`can-rx receiver=<id> id=0x07nn ...`).
//!
//! A scenario declares each probe's ground truth in a header directive:
//!
//! ```toml
//! # topology-probe: probe=0x07a0 expect=1,3
//! ```
//!
//! meaning "the frame with id 0x07a0 must be received by exactly machines 1 and
//! 3, each once". `expect=` with no ids means the frame must reach nobody.
//!
//! ## Deferred to later milestones
//!
//! The plan's `topology` assertions "forwarded frame preserves correlation id"
//! and "trace includes source *and* destination component identity" need
//! costar's Trace v2 (correlation ids + per-event source/dest identity) and
//! gateway frame *forwarding* — neither exists yet. The `drive_body_bus_bridge`
//! and `gateway_loop_prevention` scenarios (which require gateway forwarding)
//! and `fleet_64_nodes` are therefore deferred to the Trace-v2 / gateway-bridge
//! milestone. What is asserted here — routing, isolation, no-duplication — is
//! the foundation those build on, and it is backed by the costar
//! `test_firmware_can_tx_respects_bus_membership` engine test.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::time::Duration;

use crate::json::Json;
use crate::runner::run_scenario;

/// Default corpus directory, relative to the microcar repo root.
pub const DEFAULT_TOPOLOGY_DIR: &str = "dogfood/topology";

/// A declared probe: a unique CAN id and the exact set of machine ids that must
/// receive it (each exactly once).
#[derive(Debug, Clone)]
pub struct Probe {
    pub id: u32,
    pub id_hex: String,
    pub expect: BTreeSet<u64>,
}

/// Result of evaluating one probe against a scenario's trace.
#[derive(Debug, Clone)]
pub struct ProbeResult {
    pub id_hex: String,
    pub expected: BTreeSet<u64>,
    /// receiver id -> number of `can-rx` events observed for this probe id.
    pub actual: BTreeMap<u64, usize>,
    pub passed: bool,
    pub detail: String,
}

/// Result of one topology scenario (all its probes).
#[derive(Debug, Clone)]
pub struct TopologyScenarioResult {
    pub name: String,
    pub probes: Vec<ProbeResult>,
    /// True if the scenario ran cleanly and every probe passed.
    pub passed: bool,
    /// Non-empty if the run itself failed (bad exit, panic, timeout).
    pub run_error: Option<String>,
}

/// The whole topology lane result.
#[derive(Debug, Clone)]
pub struct TopologyReport {
    pub scenarios: Vec<TopologyScenarioResult>,
}

impl TopologyReport {
    pub fn totals(&self) -> (usize, usize) {
        let passed = self.scenarios.iter().filter(|s| s.passed).count();
        (passed, self.scenarios.len() - passed)
    }

    pub fn passed(&self) -> bool {
        !self.scenarios.is_empty() && self.scenarios.iter().all(|s| s.passed)
    }

    pub fn to_json(&self) -> Json {
        let scenarios = self
            .scenarios
            .iter()
            .map(|s| {
                let probes = s
                    .probes
                    .iter()
                    .map(|p| {
                        let actual: Vec<Json> = p
                            .actual
                            .iter()
                            .map(|(r, c)| {
                                Json::Obj(vec![
                                    ("receiver".into(), Json::UInt(*r as u128)),
                                    ("count".into(), Json::UInt(*c as u128)),
                                ])
                            })
                            .collect();
                        Json::Obj(vec![
                            ("id".into(), Json::str(&p.id_hex)),
                            (
                                "expected".into(),
                                Json::Arr(p.expected.iter().map(|r| Json::UInt(*r as u128)).collect()),
                            ),
                            ("actual".into(), Json::Arr(actual)),
                            ("passed".into(), Json::Bool(p.passed)),
                            ("detail".into(), Json::str(&p.detail)),
                        ])
                    })
                    .collect();
                let mut fields = vec![
                    ("name".into(), Json::str(&s.name)),
                    ("passed".into(), Json::Bool(s.passed)),
                    ("probes".into(), Json::Arr(probes)),
                ];
                if let Some(e) = &s.run_error {
                    fields.push(("run_error".into(), Json::str(e)));
                }
                Json::Obj(fields)
            })
            .collect();
        let (passed, failed) = self.totals();
        Json::Obj(vec![
            ("lane".into(), Json::str("topology")),
            ("passed".into(), Json::Bool(self.passed())),
            ("scenarios_passed".into(), Json::UInt(passed as u128)),
            ("scenarios_failed".into(), Json::UInt(failed as u128)),
            ("scenarios".into(), Json::Arr(scenarios)),
        ])
    }
}

/// Parse `# topology-probe: probe=0xNNNN expect=a,b,c` directives from a
/// scenario file's header comments. Reads raw text (no TOML parse needed).
pub fn parse_probes(path: &Path) -> io::Result<Vec<Probe>> {
    let content = fs::read_to_string(path)?;
    let mut probes = Vec::new();
    for line in content.lines() {
        let t = line.trim_start();
        let Some(rest) = t.strip_prefix("# topology-probe:") else {
            continue;
        };
        let mut id: Option<u32> = None;
        let mut id_hex = String::new();
        let mut expect = BTreeSet::new();
        for tok in rest.split_whitespace() {
            if let Some(v) = tok.strip_prefix("probe=") {
                id = parse_hex_u32(v);
                id_hex = normalize_hex(v);
            } else if let Some(v) = tok.strip_prefix("expect=") {
                for r in v.split(',') {
                    let r = r.trim();
                    if !r.is_empty() {
                        if let Ok(n) = r.parse::<u64>() {
                            expect.insert(n);
                        }
                    }
                }
            }
        }
        if let Some(id) = id {
            probes.push(Probe { id, id_hex, expect });
        }
    }
    Ok(probes)
}

/// Parse `key=0x...` / `key=NNN` into a u32. Accepts hex (0x-prefixed) or decimal.
fn parse_hex_u32(s: &str) -> Option<u32> {
    let s = s.trim();
    if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        u32::from_str_radix(hex, 16).ok()
    } else {
        s.parse::<u32>().ok()
    }
}

/// Render a probe id the way the trace does: `id={:#06x}`.
fn normalize_hex(s: &str) -> String {
    match parse_hex_u32(s) {
        Some(n) => format!("{n:#06x}"),
        None => s.to_string(),
    }
}

/// Parse a `can-rx receiver=<n> id=0x.... len=..` trace line into (receiver, id).
pub fn parse_can_rx(line: &str) -> Option<(u64, u32)> {
    if !line.contains("can-rx") {
        return None;
    }
    let mut receiver: Option<u64> = None;
    let mut id: Option<u32> = None;
    for tok in line.split_whitespace() {
        if let Some(v) = tok.strip_prefix("receiver=") {
            receiver = v.parse::<u64>().ok();
        } else if let Some(v) = tok.strip_prefix("id=") {
            id = parse_hex_u32(v);
        }
    }
    match (receiver, id) {
        (Some(r), Some(i)) => Some((r, i)),
        _ => None,
    }
}

/// Evaluate one probe against the (receiver-id -> count) map derived from the
/// trace's `can-rx` events for that probe id.
fn evaluate_probe(probe: &Probe, actual: BTreeMap<u64, usize>) -> ProbeResult {
    let actual_set: BTreeSet<u64> = actual.keys().copied().collect();
    let set_matches = actual_set == probe.expect;
    let no_dupes = actual.values().all(|c| *c == 1);
    let passed = set_matches && no_dupes;

    let detail = if passed {
        if probe.expect.is_empty() {
            "no receivers (as expected)".to_string()
        } else {
            format!("received once by exactly {:?}", probe.expect)
        }
    } else if !set_matches {
        let unexpected: BTreeSet<u64> = actual_set.difference(&probe.expect).copied().collect();
        let missing: BTreeSet<u64> = probe.expect.difference(&actual_set).copied().collect();
        format!(
            "receiver mismatch: expected {:?}, got {:?} (unexpected={:?}, missing={:?})",
            probe.expect, actual_set, unexpected, missing
        )
    } else {
        let dupes: Vec<(u64, usize)> =
            actual.iter().filter(|(_, c)| **c != 1).map(|(r, c)| (*r, *c)).collect();
        format!("duplicate injection: {dupes:?}")
    };

    ProbeResult {
        id_hex: probe.id_hex.clone(),
        expected: probe.expect.clone(),
        actual,
        passed,
        detail,
    }
}

/// Run one topology scenario and evaluate all its probes.
pub fn run_topology_scenario(bin: &Path, scenario: &Path, timeout: Duration) -> TopologyScenarioResult {
    let probes = parse_probes(scenario).unwrap_or_default();
    let run = run_scenario(bin, scenario, timeout);
    let name = run.scenario.clone();

    let run_error = if run.status != crate::runner::RunStatus::Pass {
        Some(format!(
            "scenario did not run cleanly: {} (exit {:?})",
            run.status.as_str(),
            run.exit_code
        ))
    } else {
        None
    };

    // Build per-id receiver histograms once.
    let mut by_id: BTreeMap<u32, BTreeMap<u64, usize>> = BTreeMap::new();
    for line in &run.trace {
        if let Some((receiver, id)) = parse_can_rx(line) {
            *by_id.entry(id).or_default().entry(receiver).or_default() += 1;
        }
    }

    let mut probe_results = Vec::with_capacity(probes.len());
    for probe in &probes {
        let actual = by_id.get(&probe.id).cloned().unwrap_or_default();
        probe_results.push(evaluate_probe(probe, actual));
    }

    let passed = run_error.is_none()
        && !probe_results.is_empty()
        && probe_results.iter().all(|p| p.passed);

    TopologyScenarioResult {
        name,
        probes: probe_results,
        passed,
        run_error,
    }
}

/// Discover topology scenarios (every `*.toml` carrying a `# topology-probe:`
/// directive) in `dir`, sorted for determinism.
pub fn discover_scenarios(dir: &Path) -> io::Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.extension().and_then(|e| e.to_str()) != Some("toml") {
            continue;
        }
        if parse_probes(&path)?.is_empty() {
            continue;
        }
        out.push(path);
    }
    out.sort();
    Ok(out)
}

/// Run every topology scenario in `dir`.
pub fn run_topology(bin: &Path, dir: &Path, timeout: Duration) -> io::Result<TopologyReport> {
    let scenarios = discover_scenarios(dir)?;
    let results = scenarios
        .iter()
        .map(|s| run_topology_scenario(bin, s, timeout))
        .collect();
    Ok(TopologyReport { scenarios: results })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_can_rx_extracts_receiver_and_id() {
        let line = "[machine.3]          500 can-rx receiver=3 id=0x07a0 len=1";
        assert_eq!(parse_can_rx(line), Some((3, 0x07a0)));
        assert_eq!(parse_can_rx("[machine.1] 10 can-tx sender=1 id=0x0001 len=5"), None);
        assert_eq!(parse_can_rx("PASS"), None);
    }

    #[test]
    fn probe_passes_on_exact_set_each_once() {
        let probe = Probe {
            id: 0x07a0,
            id_hex: "0x07a0".into(),
            expect: BTreeSet::from([1u64, 3u64]),
        };
        let actual = BTreeMap::from([(1u64, 1usize), (3u64, 1usize)]);
        assert!(evaluate_probe(&probe, actual).passed);
    }

    #[test]
    fn probe_fails_on_unexpected_receiver() {
        let probe = Probe {
            id: 0x07a0,
            id_hex: "0x07a0".into(),
            expect: BTreeSet::from([1u64]),
        };
        // machine 4 (other bus) leaked -> fail.
        let actual = BTreeMap::from([(1u64, 1usize), (4u64, 1usize)]);
        let r = evaluate_probe(&probe, actual);
        assert!(!r.passed);
        assert!(r.detail.contains("unexpected"));
    }

    #[test]
    fn probe_fails_on_missing_receiver() {
        let probe = Probe {
            id: 0x07a0,
            id_hex: "0x07a0".into(),
            expect: BTreeSet::from([1u64, 3u64]),
        };
        let actual = BTreeMap::from([(1u64, 1usize)]);
        assert!(!evaluate_probe(&probe, actual).passed);
    }

    #[test]
    fn probe_fails_on_duplicate_injection() {
        let probe = Probe {
            id: 0x07a0,
            id_hex: "0x07a0".into(),
            expect: BTreeSet::from([1u64]),
        };
        let actual = BTreeMap::from([(1u64, 2usize)]);
        let r = evaluate_probe(&probe, actual);
        assert!(!r.passed);
        assert!(r.detail.contains("duplicate"));
    }

    #[test]
    fn empty_expect_means_no_receivers() {
        let probe = Probe {
            id: 0x07a0,
            id_hex: "0x07a0".into(),
            expect: BTreeSet::new(),
        };
        assert!(evaluate_probe(&probe, BTreeMap::new()).passed);
        // Any receiver is a failure when none are expected.
        assert!(!evaluate_probe(&probe, BTreeMap::from([(1u64, 1usize)])).passed);
    }

    #[test]
    fn parse_hex_handles_hex_and_decimal() {
        assert_eq!(parse_hex_u32("0x07a0"), Some(0x07a0));
        assert_eq!(parse_hex_u32("1952"), Some(1952));
        assert_eq!(normalize_hex("0x7a0"), "0x07a0");
    }
}
